---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include_tasks: user.yml
  when: nomad_create_user
  tags: nomad_user

- include_tasks: provision.yml
  tags: nomad_provision

- include_tasks: install.yml
  tags: nomad_install

- include_tasks: config.yml
  tags: nomad_config

- include_tasks: service.yml
  tags: nomad_service

# vi:ts=2:sw=2:et:ft=yaml
